name: Node CI

on: [push]

jobs:
 Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: scp a produccio
        run: |
          cd ./web/vue-project
          npm run build
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./web/vue-project/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/a20erigomvil/web/a20erigomvil.daw.inspedralbes.cat/public_html/vue
          
      - run: echo "🍏 This job's status is ${{ job.status }}."